// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mizan.Models;

#nullable disable

namespace Mizan.Migrations
{
    [DbContext(typeof(MizanDbContext))]
    [Migration("20260823150258_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mizan.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT")
                        .HasColumnName("institution");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LiquidityClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("liquidity_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("OpeningBalanceMinor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_balance_minor");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_date");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.ToTable("account", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_liquidity_class", "liquidity_class IN ('immediate','short_term','illiquid','debt')");

                            t.HasCheckConstraint("CK_account_type", "type IN ('cash','bank','card','broker','loan','physical_asset','receivable','other')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_parent_id");

                    b.ToTable("category", null, t =>
                        {
                            t.HasCheckConstraint("CK_category_kind", "kind IN ('income','expense','transfer','investment','adjustment')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.Txn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_minor");

                    b.Property<DateOnly?>("BookedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("booked_on");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("DescriptionNorm")
                        .HasColumnType("TEXT")
                        .HasColumnName("description_norm");

                    b.Property<string>("DescriptionRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description_raw");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_void");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<int?>("ParentTxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_txn_id");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superseded_by_id");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("void_reason");

                    b.HasKey("Id")
                        .HasName("pk_txn");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_txn_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_txn_category_id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_txn_dedupe_key")
                        .HasFilter("superseded_by_id IS NULL AND is_void = 0");

                    b.HasIndex("ParentTxnId")
                        .HasDatabaseName("ix_txn_parent_txn_id");

                    b.HasIndex("SupersededById")
                        .HasDatabaseName("ix_txn_superseded_by_id");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_txn_supersedes_id");

                    b.ToTable("txn", null, t =>
                        {
                            t.HasCheckConstraint("CK_txn_origin", "origin IN ('import','manual','split','adjustment','seed')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.Category", b =>
                {
                    b.HasOne("Mizan.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Mizan.Models.Txn", b =>
                {
                    b.HasOne("Mizan.Models.Account", "Account")
                        .WithMany("Txns")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_account_account_id");

                    b.HasOne("Mizan.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_txn_category_category_id");

                    b.HasOne("Mizan.Models.Txn", null)
                        .WithMany()
                        .HasForeignKey("ParentTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_txn_txn_parent_txn_id");

                    b.HasOne("Mizan.Models.Txn", null)
                        .WithMany()
                        .HasForeignKey("SupersededById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_txn_txn_superseded_by_id");

                    b.HasOne("Mizan.Models.Txn", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_txn_txn_supersedes_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mizan.Models.Account", b =>
                {
                    b.Navigation("Txns");
                });
#pragma warning restore 612, 618
        }
    }
}
