// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mizan.Models;

#nullable disable

namespace Mizan.Migrations
{
    [DbContext(typeof(MizanDbContext))]
    [Migration("20260823162321_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mizan.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT")
                        .HasColumnName("institution");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LiquidityClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("liquidity_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<long>("OpeningBalanceMinor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_balance_minor");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_date");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_account_name");

                    b.ToTable("account", null, t =>
                        {
                            t.HasCheckConstraint("CK_account_liquidity_class", "liquidity_class IN ('immediate','short_term','illiquid','debt')");

                            t.HasCheckConstraint("CK_account_type", "type IN ('cash','bank','card','broker','loan','physical_asset','receivable','other')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_parent_id");

                    b.ToTable("category", null, t =>
                        {
                            t.HasCheckConstraint("CK_category_kind", "kind IN ('income','expense','transfer','investment','adjustment')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.Txn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_minor");

                    b.Property<DateOnly?>("BookedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("booked_on");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("DescriptionNorm")
                        .HasColumnType("TEXT")
                        .HasColumnName("description_norm");

                    b.Property<string>("DescriptionRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description_raw");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<string>("SourceDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_detail");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_txn");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_txn_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_txn_category_id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_txn_dedupe_key");

                    b.ToTable("txn", null, t =>
                        {
                            t.HasCheckConstraint("CK_txn_origin", "origin IN ('import','manual','split','adjustment','seed')");
                        });
                });

            modelBuilder.Entity("Mizan.Models.TxnSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChildTxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("child_txn_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<int>("ParentTxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_txn_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_txn_split");

                    b.HasIndex("ChildTxnId")
                        .HasDatabaseName("ix_txn_split_child_txn_id");

                    b.HasIndex("ParentTxnId")
                        .HasDatabaseName("ix_txn_split_parent_txn_id");

                    b.ToTable("txn_split", (string)null);
                });

            modelBuilder.Entity("Mizan.Models.TxnSupersession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<int>("NewTxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_txn_id");

                    b.Property<int>("OldTxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("old_txn_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_txn_supersession");

                    b.HasIndex("NewTxnId")
                        .HasDatabaseName("ix_txn_supersession_new_txn_id");

                    b.HasIndex("OldTxnId")
                        .HasDatabaseName("ix_txn_supersession_old_txn_id");

                    b.ToTable("txn_supersession", (string)null);
                });

            modelBuilder.Entity("Mizan.Models.TxnVoid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("TxnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("txn_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.HasKey("Id")
                        .HasName("pk_txn_void");

                    b.HasIndex("TxnId")
                        .HasDatabaseName("ix_txn_void_txn_id");

                    b.ToTable("txn_void", (string)null);
                });

            modelBuilder.Entity("Mizan.Models.Category", b =>
                {
                    b.HasOne("Mizan.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Mizan.Models.Txn", b =>
                {
                    b.HasOne("Mizan.Models.Account", "Account")
                        .WithMany("Txns")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_account_account_id");

                    b.HasOne("Mizan.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_txn_category_category_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mizan.Models.TxnSplit", b =>
                {
                    b.HasOne("Mizan.Models.Txn", "ChildTxn")
                        .WithMany()
                        .HasForeignKey("ChildTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_split_txn_child_txn_id");

                    b.HasOne("Mizan.Models.Txn", "ParentTxn")
                        .WithMany()
                        .HasForeignKey("ParentTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_split_txn_parent_txn_id");

                    b.Navigation("ChildTxn");

                    b.Navigation("ParentTxn");
                });

            modelBuilder.Entity("Mizan.Models.TxnSupersession", b =>
                {
                    b.HasOne("Mizan.Models.Txn", "NewTxn")
                        .WithMany()
                        .HasForeignKey("NewTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_supersession_txn_new_txn_id");

                    b.HasOne("Mizan.Models.Txn", "OldTxn")
                        .WithMany()
                        .HasForeignKey("OldTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_supersession_txn_old_txn_id");

                    b.Navigation("NewTxn");

                    b.Navigation("OldTxn");
                });

            modelBuilder.Entity("Mizan.Models.TxnVoid", b =>
                {
                    b.HasOne("Mizan.Models.Txn", "Txn")
                        .WithMany()
                        .HasForeignKey("TxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_txn_void_txn_txn_id");

                    b.Navigation("Txn");
                });

            modelBuilder.Entity("Mizan.Models.Account", b =>
                {
                    b.Navigation("Txns");
                });
#pragma warning restore 612, 618
        }
    }
}
